### ISSUE TITLE
а можно скидку русским

### ISSUE THREAD

**Issue by mr-nv** [TheKisDevs/LavaHack#1]

**Comment by kisman2000** [comment]
nu ok

**Comment by mr-nv** [comment]
где

**Comment by kisman2000** [comment]
https://github.com/TheKisDevs/kisman.cc-public

**Comment by mr-nv** [comment]
так это старые версии а я новейшую хочу

пн, 18 апр. 2022 г., 6:16 kisman ***@***.***>:

**Comment by mr-nv** [comment]
Гоу за пицот рублей у тебя все равно это никто не купит кроме араба который все скупает
